name: taxi
description: Drop Off and Delivery Management

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.2

    # SQLite plugin for Flutter. Supports both iOS and Android.
    # https://pub.dev/packages/sqflite
    sqflite: ^1.1.6+2

    # A dependency injection system built with widgets for widgets.
    # provider is mostly syntax sugar for InheritedWidget, to make common use-cases straightforward.
    # https://pub.dev/packages/provider
    provider: ^3.0.0+1

    # A Flutter plugin for finding commonly used locations on the filesystem. Supports iOS and Android.
    # https://pub.dev/packages/path_provider
    path_provider: ^1.1.2

    # A comprehensive, cross-platform path manipulation library for Dart.
    # The path package provides common operations for manipulating paths: joining, splitting, normalizing, etc
    # https://pub.dev/packages/path
    path: 1.6.2

    #This package provides internationalization and localization facilities,
    # including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
    intl: ^0.15.8

dev_dependencies:
    flutter_test:
        sdk: flutter
    # A command-line tool which simplifies the task of updating your Flutter app's launcher icon.
    # Fully flexible, allowing you to choose what platform you wish to update the launcher icon for and if you want,
    # the option to keep your old launcher icon in case you want to revert back sometime in the future.
    # https://pub.dev/packages/flutter_launcher_icons
    flutter_launcher_icons: ^0.7.2

flutter_icons:
    image_path: assets/icon.png
    ios: true
    android: "launcher_icon"
    adaptive_icon_background: "#ffbf00"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
